In [1]:
# required libraries
import pandas
import csv
import numpy


In [5]:
# loading data using csv library using iris dataset
import numpy as np
path =r"C:\Users\DELL\Downloads\INTERN\IRIS.csv"
with open(path,'r') as f:
    reader =csv.reader(f,delimiter=',')
    headers=next(reader)
    data=list(reader)
    data=np.array(data).astype(float)
print(data.shape)
print(headers)
print(data[:3])

(150, 4)
['sepal.length', 'sepal.width', 'petal.length', 'petal.width']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [7]:
# loading data with csv library using dibeties dataset
path=r"C:\Users\DELL\Downloads\INTERN\pima-indians-diabetes.csv"
with open(path,'r') as f:
    reader=csv.reader(f,delimiter=',')
    data=list(reader)
    data=np.array(data).astype(float)
print(data.shape)
print(data[:3])

(768, 9)
[[  6.    148.     72.     35.      0.     33.6     0.627  50.      1.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.      0.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.      1.   ]]


In [8]:
# loading data using numpy library using diabeties dataset
from numpy import loadtxt
path =r"C:\Users\DELL\Downloads\INTERN\pima-indians-diabetes.csv"
datapath =open(path,'r')
data = loadtxt(datapath,delimiter =',')
print(data.shape)
print(data[:3])

(768, 9)
[[  6.    148.     72.     35.      0.     33.6     0.627  50.      1.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.      0.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.      1.   ]]


In [9]:
# loading data using numpy library using iris dataset
import numpy as np
data =  np.genfromtxt(r"C:\Users\DELL\Downloads\INTERN\IRIS.csv" , delimiter =',',skip_header=1)
header = np.genfromtxt(r"C:\Users\DELL\Downloads\INTERN\IRIS.csv",delimiter =',',dtype='str',max_rows=1)   
print(data.shape)
print(header)
print(data[:3])

(150, 4)
['sepal.length' 'sepal.width' 'petal.length' 'petal.width']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [13]:
#loading data using pandas library using iris dataset
from pandas import read_csv
path=r"C:\Users\DELL\Downloads\INTERN\IRIS.csv"
data = read_csv(path)
print(data.shape) 
print(data[:3])
print(data.head())

(150, 4)
   sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
   sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [15]:
# loading data using pandas library using diabeties dataset
path=r"C:\Users\DELL\Downloads\INTERN\pima-indians-diabetes.csv"
headernames = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data=read_csv(path,names=headernames)
print(data.shape)
print(data[:3])

(768, 9)
   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
